---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0750
  loop:
    - "{{ postgresql_data_dir }}"
  notify: restart postgresql server

- name: Configure postgresql
  template:
    src: "{{ item }}.j2"
    dest: /etc/postgresql/11/main/{{ item }}
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    backup: yes
    mode: 0640
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify: restart postgresql server

# TODO: Add replication conf

- name: Start postgresql service
  systemd:
    name: postgresql
    state: started
    daemon_reload: yes
    enabled: yes
  register: postgresql_started
