---
- name: Create postgres replication user
  postgresql_user:
    name: "repluser"
    password: "{{ postgresql_repl_pass }}"
    role_attr_flags: replication

- name: Create postgres dev users
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
  with_items: "{{ postgresql_dbs }}"

- name: Grant priveleges for dev users
  postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
  with_items: "{{ postgresql_dbs }}"

- name: Grant priveleges for dev users
  postgresql_privs:
    db: "{{ item.name }}"
    role: "{{ item.user }}"
    objs: ALL_IN_SCHEMA
    privs: ALL
  with_items: "{{ postgresql_dbs }}"
