---
- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

- name: Restart node_exporter service
  service:
    name: node_exporter
    state: restarted
  listen: node_exporter_restart
