---
- name: install nginx
  package:
    name: nginx
    state: latest

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify:
    - nginx_reload

- name: create path for configs
  file:
    path: /etc/nginx/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: configure nginx default site
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    backup: yes
  notify: nginx_reload

- name: create path for whitelist
  file:
    path: /etc/nginx/whitelist/
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: configure nginx whitelist
  template:
    src: "whitelist/{{ item }}-whitelist.conf.j2"
    dest: "/etc/nginx/whitelist/{{ item }}-whitelist.conf"
    backup: yes
  with_items:
    - main
    - office
  notify: nginx_reload

- name: configure nginx main sites
  template:
    src: nginx-site.conf.j2
    dest: /etc/nginx/conf.d/{{ item.name }}.conf
    backup: yes
  vars:
    server_names: "{{ groups['web_servers'] }}"
  with_items:
    - name: dashboard
      port: 8888
      server_name: dashboard.assol.ml
      # ssl_certificate: /etc/letsencrypt/live/assol.ml/fullchain.pem;
      # ssl_certificate_key: /etc/letsencrypt/live/assol.ml/privkey.pem;
  notify: nginx_reload

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
