---
- name: Installing HAProxy
  package:
    name: haproxy
    state: present
  notify: restart haproxy

- include: checkers.yml

- name: Generate haproxy systemd unit
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
    backup: yes
  with_items:
    - { src: haproxy.service.j2, dest: /lib/systemd/system/haproxy.service, mode: '0644' }
  notify: restart haproxy

- name: Creates config directory
  file: 
    path: "/etc/haproxy/conf.d"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0755

- name: Generate config
  vars:
    mysql_server_names: "{{ groups[db_group] }}"
    postgresql_server_names: "{{ groups[db_group] }}"
    memcached_server_names: "{{ groups[memcached_group] }}"
    redis_server_names: "{{ groups[redis_group] }}"
    razumator_server_names: "{{ groups[razumator_core_group] }}"
    mqtt_server_names: "{{ groups[mqtt_group] }}"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
  notify: reload haproxy

- name: Start and enable HAProxy
  systemd:
    name: haproxy
    state: started
    daemon_reload: yes
    enabled: yes
  register: haproxy_started

- name: Flush handlers
  meta: flush_handlers
