---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0755
  loop:
    - "{{ consul_data_dir }}"
    - "{{ consul_log_dir }}"
    - /etc/consul
    - /etc/consul/services
  notify: restart consul server

- name: Create systemd unit
  template:
    src: consul-systemd.j2
    dest: /etc/systemd/system/consul.service
  notify: restart consul server

- name: Configure Consul
  template:
    src: consul_conf.hcl.j2
    dest: /etc/consul/consul.hcl
    owner: consul
    backup: yes
  notify: reload consul server

- name: Start consul service
  systemd:
    name: consul
    state: started
    daemon_reload: yes
    enabled: yes
    no_block: "{{ consul_server }}"
  register: consul_started
