---
- name: Creates config directory
  file: 
    path: "{{ alertmanager_bot_conf_dir }}"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Creates bolt directory
  file: 
    path: "{{ alertmanager_bot_boltdir }}"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
    mode: 0640
  notify: restart alertmanager_bot

- name: Copy message template
  copy:
    src: files/default.tmpl
    dest: "{{ alertmanager_bot_conf_dir }}/default.tmpl"
    owner: root
    group: root
    mode: 0644
  notify: restart alertmanager_bot

- name: Copy test script
  template:
    src: test_alerts.sh
    dest: /root/test_alerts.sh
    owner: root
    group: root
    mode: 0750

- name: Start alertmanager_bot service
  systemd:
    name: "{{ service_name }}"
    state: started
    daemon_reload: yes
    enabled: yes
  register: alertmanager_bot_started
