---
- name: Download alertmanager-bot release to local folder
  become: false
  get_url:
    url: "{{ alertmanager_bot_download_url }}"
    dest: "/tmp/alertmanager_bot"
  register: _download_bin
  until: _download_bin is succeeded
  retries: 3
  delay: 2
  run_once: true
  delegate_to: localhost
  check_mode: false

- name: Creating alertmanager-bot user group
  group: name="{{groupId}}"
  when: groupId != "root"

- name: Creating alertmanager-bot user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present
  when: userId != "root"

- name: Copy alertmanager-bot binaries
  copy:
    src: "/tmp/alertmanager_bot"
    dest: "{{ alertmanager_bot_bin_dir }}/"
    mode: 0755
    owner: "{{ userId }}"
    group: "{{ groupId }}"
  notify: restart alertmanager_bot
