---
- name: Copy repo file
  copy:
    src: grafana.list
    dest: /etc/apt/sources.list.d/grafana.list
    mode: 0755
    owner: root
    group: root

- name: Add an APT signing key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Update APT cache
  apt:
    update_cache: yes
  changed_when: no

- name: Install packages
  package:
    name:
      - grafana
    state: present
  notify: restart grafana
