---
- name: Install uwsgi
  package:
    name: uwsgi
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python3

- name: Start and enable uwsgi-apps
  systemd:
    name: uwsgi
    state: started
    enabled: yes

# TODO
