- src: git@bmstu.codes:iu5/infrastructure/dashboards-role.git
  name: dashboards
  scm: git

- src: git@bmstu.codes:iu5/infrastructure/format-tester-role.git
  name: format_tester
  scm: git

- src: git@github.com:SnipGhost/ansible-role-pi-openvpn.git
  name: openvpn
  scm: git
