---
- hosts: all
  roles:
    - name: common
      tags: common
    - name: sshd
      tags: sshd
    - name: iptables
      tags: iptables
    - name: keepalived
      tags: keepalived

- hosts: dns_servers
  roles:
    - name: dnsmasq
      tags: dnsmasq

- hosts: monitoring_servers
  roles:
    - name: prometheus
      tags: prometheus
    - name: grafana
      tags: grafana

- hosts: all
  roles:
    - name: node_exporter
      tags: node_exporter

- hosts: raspberry_pi
  roles:
    - name: rpi_fan_driver
      tags: rpi_fan_driver
    - name: rpi_exporter
      tags: rpi_exporter
