---
- hosts: db_servers
  roles:
    - name: mariadb
      tags: mariadb
    - name: mysqld_exporter
      tags: mysqld_exporter

- hosts: cache_servers
  roles:
    - name: memcached
      tags: memcached
    - name: memcached_exporter
      tags: memcached_exporter
