---
- hosts: all
  tasks:
    - debug:
        msg: "{{ lookup('dig', item + '.i', '@' + service_vip_ip) }}"
      with_items: "{{ groups['all'] }}"

    - debug:
        var: ansible_architecture

    - vars:
        pg_master_address: "{% for host in groups[db_group] %}{% if hostvars[host]['db_master'] | default(false) | bool %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}{% endif %}{% endfor %}"
      debug:
        var: pg_master_address
