---
- name: Set Boot behaviour
  shell: "raspi-config nonint do_boot_behaviour {{ BOOTBEHAVIOUR }}"

- name: Change timezone
  shell: "raspi-config nonint do_change_timezone {{ TIMEZONE }}"

- name: Change locale
  shell: "raspi-config nonint do_change_locale {{ LOCALE }}"

- name: Update APT cache
  apt:
    update_cache: yes

- name: APT upgrade
  apt:
    upgrade: yes

- name: Add ansible user
  user:
    name: "{{ ansible_user }}"
    state: present
    password: "{{ '%s' | format(passwords[ansible_user]) | password_hash('sha512') }}"

- name: Ensure groups wheel and remote exists
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - wheel
    - remote

- name: Add ansible user to wheel and remote
  user:
    name: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    groups: adm,wheel,remote,systemd-journal
    append: yes
    state: present

- name: Add ansible user to sudoers via wheel group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel  ALL=(ALL:ALL) ALL'

- name: Add public keys to authorized_key for ansible
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item.key }}"
  with_items: "{{ admins | default([]) }}"

- name: Get hostname
  shell: "raspi-config nonint get_hostname"
  register: pi_hostname
  check_mode: no
  changed_when: False

- name: Change hostname
  shell: "raspi-config nonint do_hostname {{ HOSTNAME }}"
  when: pi_hostname.stdout != HOSTNAME

- name: Configurate WiFi
  shell: "raspi-config nonint do_wifi_ssid_passphrase {{ ap_ssid }} {{ ap_pass }} && raspi-config nonint do_wifi_country {{ ap_code }}"
  when: not rpi_disable_wireless | default(false) | bool

- name: Disable wireless modules
  lineinfile:
    line: 'dtoverlay={{ item }}'
    dest: /boot/config.txt
    regexp: "^ *#? *dtoverlay={{ item }}"
    insertafter: [all]
  with_items:
    - disable-wifi
    - disable-bt
  when: rpi_disable_wireless | default(false) | bool

- name: Enable wireless modules
  lineinfile:
    line: '#dtoverlay={{ item }}'
    dest: /boot/config.txt
    regexp: "^ *#? *dtoverlay={{ item }}"
    insertafter: [all]
  with_items:
    - disable-wifi
    - disable-bt
  when: not rpi_disable_wireless | default(false) | bool

- name: Write dhcpcd config for static IP
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    backup: yes
    mode: 0664
    owner: root
    group: netdev

- command: "reboot"
  ignore_errors: yes
