---
- name: Set Boot behaviour
  shell: "raspi-config nonint do_boot_behaviour {{ BOOTBEHAVIOUR }}"

- name: Change timezone
  shell: "raspi-config nonint do_change_timezone {{ TIMEZONE }}"

- name: Change locale
  shell: "raspi-config nonint do_change_locale {{ LOCALE }}"

- name: Update APT cache
  apt:
    update_cache: yes

- name: APT upgrade
  apt:
    upgrade: yes

- name: Add ansible user
  user:
    name: ansible
    state: present
    password: "{{ '%s' | format(passwords['ansible']) | password_hash('sha512') }}"

- name: Add ansible user to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^ansible\s'
    line: 'ansible ALL=(ALL) ALL'

- name: Get hostname
  shell: "raspi-config nonint get_hostname"
  register: pi_hostname
  check_mode: no
  changed_when: False

- name: Change hostname
  shell: "raspi-config nonint do_hostname {{ HOSTNAME }}"
  when: pi_hostname.stdout != HOSTNAME

- name: Configurate WiFi
  shell: "raspi-config nonint do_wifi_ssid_passphrase {{ ap_ssid }} {{ ap_pass }} && raspi-config nonint do_wifi_country {{ ap_code }}"

- name: Write dhcpcd config for static IP
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    backup: yes
    mode: 0664
    owner: root
    group: netdev

- shell: "reboot"
  ignore_errors: yes
