---
- name: Install RPi-FanDriver script
  get_url:
    url: "https://raw.githubusercontent.com/SnipGhost/RPi-FanDriver/master/fan_driver.py"
    dest: /usr/sbin/fan_driver.py
    mode: 0755
  notify: fan_driver_restart
  when: has_fan | default('false') | bool

- name: Install RPi-FanDriver systemd-unit
  get_url:
    url: https://raw.githubusercontent.com/SnipGhost/RPi-FanDriver/master/fan-driver.service
    dest: /etc/systemd/system/fan-driver.service
    mode: 0644
  notify: systemd_reload
  when: has_fan | default('false') | bool

- name: Create config
  template:
    src: fan_driver.config.json.j2
    dest: /etc/fan_driver.config.json
    backup: yes
    mode: 0644
  notify: fan_driver_reload
  when: has_fan | default('false') | bool

- name: Check that systemd unit exists
  stat:
    path: /etc/systemd/system/fan-driver.service
  register: stat_result
  check_mode: no
  when: not (has_fan | default('false') | bool)

- name: Stop RPi-FanDriver service
  service:
    name: fan-driver
    state: stopped
    enabled: no
  when: not (has_fan | default('false') | bool) and stat_result.stat.exists

- meta: flush_handlers

- name: Start RPi-FanDriver service
  service:
    name: fan-driver
    state: started
    enabled: yes
  when: has_fan | default('false') | bool

