[dev_db_servers]
itsuki db_master=yes db_replication=no

[dev_memcached_servers]
rikka

[dev_redis_servers]
itsuki redis_master=yes

[dev_web_servers]
itsuki
rikka

[dev_krionard]
rikka

[dev_dacrover]
itsuki

[dev_razumator]
rikka
