---
serviceName: nginx_exporter
userId: prometheus
groupId: prometheus

nginx_exporter_version: 0.9.0
nginx_exporter_pack_name: nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_{{ proc_version }}
nginx_exporter_pack_ext: tar.gz
nginx_exporter_download_link: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/{{ nginx_exporter_pack_name }}.{{ nginx_exporter_pack_ext }}

nginx_exporter_bin_dir: /usr/local/bin
nginx_exporter_scrape_uri: http://127.0.0.1/stub_status
exec_command: "{{ nginx_exporter_bin_dir }}/nginx_exporter -nginx.scrape-uri {{ nginx_exporter_scrape_uri }}"
