---
- name: Install packages
  package:
    name:
      - iptables-persistent
    state: present

- name: Install additional route
  template:
    src: vpn-routes.j2
    dest: /lib/dhcpcd/dhcpcd-hooks/40-router
  notify: dhcpcd restart
  when: openvpn_enabled | default('false') | bool

- name: Create rules files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/iptables/{{ item }}"
  with_items:
    - rules.v4
    - rules.v6
  notify: iptables_reload

- name: Auto-load rules on boot
  copy:
    src: iptables
    dest: /etc/network/if-up.d/iptables
    owner: root
    group: root
    mode: 0755

- meta: flush_handlers
