---
- name: Install packages
  package:
    name:
      - logrotate
    state: present

- name: Copy config file
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
  notify: logrotate_restart

- name: Start and enable logrotate
  systemd:
    name: logrotate
    state: started
    enabled: yes
