# atop
atop_log_interval: 300
atop_log_generations: 10

# Logrotate
logrotate_default_period: weekly
logrotate_default_rotate: 4

# Rsyslog
rsyslog_remote_log_dir: /mnt/data/log
rsyslog_log_period: daily
rsyslog_log_rotate: 7
rsyslog_log_size: 100M
rsyslog_send_facility:
  - auth
  - authpriv
  - local0
  - local7
rsyslog_send_severity:
  - '*'
rsyslog_server_udp: no
rsyslog_server_tcp: yes
rsyslog_remote_allowed:
  - 127.0.0.1
  - 192.168.8.0/24
