# Main options

# Summary
project_version: v0.7c

# Users with sudo
admins:
  - name: mak
    color: "01;33m"
    comment: "Mikhail Kucherenko"
    email: "makucherenko@list.ru"
    key: "https://github.com/snipghost.keys"
  - name: horifox
    color: "01;32m"
    comment: "Tagir Khanmurzin"
    email: "lhorifoxl@gmail.com"
    git_name: HoriFox
    key: "https://github.com/horifox.keys"
# Non-privileged users
users:
  - name: rgbaybarin
    color: "01;36m"
    comment: "Roman Baybarin"
    email: "rbaybarin@gmail.com"
    git_name: RBizonDota
    key: "https://github.com/RBizonDota.keys"
    servers_group: dev

# locale.gen
locales:
  - { code: "en_US.UTF-8" }
  - { code: "ru_RU.UTF-8" }

# Path to SSD-disks for all disk-based services
data_path: "/mnt/data"

# Chronyd options
ntpd_servers:
  - ntp1.mail.ru
  - ntp2.mail.ru

# Local DNS via dnsmasq
dnsmasq_records_file: /etc/cluster-hosts
dnsmasq_exporter_enabled: no
dnsmasq_logging: no
dnsmasq_iface: eth0:{{ service_vip_id }}
# DNS records in dns.yml

# Backup scripts
backup_scripts:
  - tpl: backup-db
    interval: daily
    group: monitoring_servers
    retention: 3
    important_databases:
      - dacrover
      - krionardtech
      - mysql
  - tpl: backup-grafana
    interval: daily
    group: monitoring_servers
    retention: 3

# rsyncd
rsync_users:
  - name: "{{ rsync_certs_user }}"
    password: "{{ rsync_certs_pass }}"
# sections in config
rsync_modules:
  - name: certs_live
    uid: root
    gid: root
    path: /etc/letsencrypt/live/
    comment: SSL certs links
    ro: yes
    list: yes
    users:
      - "{{ rsync_certs_user }}"
    has_secrets: yes
    group: all
  - name: certs_archive
    uid: root
    gid: root
    path: /etc/letsencrypt/archive/
    comment: SSL certs files
    ro: yes
    list: yes
    users:
      - "{{ rsync_certs_user }}"
    has_secrets: yes
    group: all

# LetsAPI
letsapi_cron_freq: weekly
letsapi_path: /etc/letsapi
cert_path: "{{ letsapi_path }}/live"
letsapi_cert_renewers:
  - host: nino
    cert: argobay.ml
  - host: rikka
    cert: dev-argobay.ml

# Consul
consul_log_level: INFO
consul_version: 1.10.1
consul_domain: compute
consul_dc: main
consul_recursors:
  - "{{ service_vip_ip }}"
consul_enable_local_script_checks: true
consul_raft_multiplier: 5
consul_dns_port: 8600
consul_http_port: 8500
consul_listen_addr:
  - 127.0.0.1

# Jupyter
jupyter_port: 8888

# Docker
docker_datapath: "{{ data_path }}/docker"
docker_runner_bridge: br_runner
docker_runner_subnet: 172.100.0.0/16
docker_bridges:
  - name: docker0
    cidr: 172.17.0.0/16
    group: all
  - name: "{{ docker_runner_bridge }}"
    cidr: "{{ docker_runner_subnet }}"
    group: gitlab_runner

# GitLab Runner
gitlab_runner_name: arm-runner
gitlab_runner_install_dir: "{{ data_path }}/runners/{{ gitlab_runner_name }}"
gitlab_runner_reg_url: https://bmstu.codes/
