# Victoria Metrics
victoria_metrics_version: 1.68.0
victoria_metrics_retention: 3
victoria_metrics_scrape_interval: 15s
victoria_metrics_evaluation_interval: 15s
victoria_metrics_host: 127.0.0.1
victoria_metrics_port: 8428
victoria_metrics_data_path: "{{ data_path }}/victoria-metrics/"

# VM Agent (merged with Victoria Metrics base)
# vmagent_host: 127.0.0.1
# vmagent_port: 8429
# vmagent_data_path: "{{ data_path }}/vmagent/"

# Rules file
victoria_metrics_rule_files:
  - main-rules.yml

# VM Alert
vmalert_host: 127.0.0.1
vmalert_port: 8880

# Add labels to hosts groups
monitoring_groups:
  - iu5

# Prometheus config drop-in replacement compatibility
prometheus_jobs:
  - { name: node, port: 9100, group: all }

# Prometheus exporter's options
node_exporter_version: 1.0.1

# Alertmanager
alertmanager_version: 0.21.0
alertmanager_bind: 0.0.0.0
alertmanager_host: 127.0.0.1
alertmanager_port: 9093
alertmanager_conf_dir: /etc/alertmanager
alertmanager_bin_dir: /usr/local/bin
alermanager_group_wait: 15s
alermanager_group_interval: 15s
alermanager_repeat_interval: 1h
alertmanager_receivers:
  - name: alertmanager-bot
    host: "{{ alertmanager_bot_host }}"
    port: "{{ alertmanager_bot_port }}"

# Alertmanager bot
alertmanager_bot_version: 0.4.3
alertmanager_bot_bind: 0.0.0.0
alertmanager_bot_host: 127.0.0.1
alertmanager_bot_port: 8007
alertmanager_bot_log_level: "info"
alertmanager_bot_conf_dir: /etc/alertmanager-bot
alertmanager_bot_boltdir: "{{ data_path }}/alertmanager-bot"
alertmanager_bot_bolt_path: "{{ alertmanager_bot_boltdir }}/storage.db"
alertmanager_bot_telegram_admins:
  - 148129813 # @snipghost
  - 425226470 # @horifox
  - 341650938 # @grisha_svch
  - 286430485 # @neughost

# Grafana
grafana_domain: grafana.doc-iu5.local.bmstu.ru
grafana_data_path: "{{ data_path }}/grafana/"
grafana_smtp_enabled: no
