###############################################################################
# DNS records generator
###############################################################################
dnsmasq_hosts:
  #========================================================
  # VIP records
  - name: public
    rec:
      - { ip: "{{public_vip_ip}}", type: i }
      - { ip: "{{dev_public_vip_ip}}", type: dev.i }

  - name: service
    rec:
      - { ip: "{{service_vip_ip}}", type: i }

  - name: private
    rec:
      - { ip: "{{private_vip_ip}}", type: i }
      - { ip: "{{dev_private_vip_ip}}", type: dev.i }

  - name: monitoring
    rec:
      - { ip: "{{monitoring_vip_ip}}", type: i }

  - name: research
    rec:
      - { ip: "{{research_vip_ip}}", type: i }

  - name: rgw
    rec:
      - { ip: "{{ rgw_lb_vip_ip }}", type: i }

  #========================================================
  # Internal subdomain records

  - name: dev-assol
    rec:
      - { ip: "{{dev_public_vip_ip}}", type: ml }

  - name: grafana
    rec:
      - { ip: "{{public_vip_ip}}", type: assol.ml }

  # - name: prometheus
  #   rec:
  #     - { ip: "{{monitoring_vip_ip}}", type: assol.ml }

  - name: vm
    rec:
      - { ip: "{{monitoring_vip_ip}}", type: assol.ml }

  - name: alertmanager
    rec:
      - { ip: "{{monitoring_vip_ip}}", type: assol.ml }

  - name: jupyter
    rec:
      - { ip: "{{research_vip_ip}}", type: assol.ml }

  - name: consul
    rec:
      - { ip: "{{consul_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_private_vip_ip}}", type: dev-assol.ml }

  - name: razumator
    rec:
      - { ip: "{{public_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_public_vip_ip}}", type: dev-assol.ml }

  - name: dacrover
    rec:
      - { ip: "{{private_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_private_vip_ip}}", type: dev-assol.ml }

  - name: krionard
    aliases:
      - marusya
      - alice
    rec:
      - { ip: "{{public_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_public_vip_ip}}", type: dev-assol.ml }
  
  - name: internal
    rec:
      - { ip: "{{private_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_private_vip_ip}}", type: dev-assol.ml }

  - name: external
    rec:
      - { ip: "{{public_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_public_vip_ip}}", type: dev-assol.ml }

  - name: swagger
    rec:
      - { ip: "{{private_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_private_vip_ip}}", type: dev-assol.ml }

  - name: wiki
    rec:
      - { ip: "{{private_vip_ip}}", type: assol.ml }
      - { ip: "{{dev_private_vip_ip}}", type: dev-assol.ml }

  #========================================================
  # Network devices

  - name: router
    rec:
      - { ip: 192.168.8.1, type: i }

  - name: switch-main
    rec:
      - { ip: 192.168.8.2, type: i }

  - name: switch-cluster
    rec:
      - { ip: 192.168.8.3, type: i }

  - name: switch-mak
    rec:
      - { ip: 192.168.8.4, type: i }

  - name: switch-horifox
    rec:
      - { ip: 192.168.8.5, type: i }
      
  #========================================================
  # IoT devices

  - name: pilot
    rec:
      - { ip: 192.168.8.201, type: i }
      - { ip: 192.168.8.201, type: assol.ml }
  
  - name: main.light
    rec:
      - { ip: 192.168.8.117, type: i }
      - { ip: 192.168.8.117, type: assol.ml }

  - name: small.light
    rec:
      - { ip: 192.168.8.235, type: i }
      - { ip: 192.168.8.235, type: assol.ml }

  - name: nyanko
    rec:
      - { ip: 192.168.8.121, type: i }
      - { ip: 192.168.8.121, type: assol.ml }

  - name: printer
    rec:
      - { ip: 192.168.8.8, type: i }
      - { ip: 192.168.8.8, type: assol.ml }

  #========================================================
  # Servers interfaces

  - name: asuna 
    rec:
      - { ip: 192.168.8.50, type: e, main: yes }
      - { ip: 192.168.8.60, type: w }

  - name: ichika
    rec:
      - { ip: 192.168.8.51, type: e }
      - { ip: 192.168.8.61, type: w, main: yes }

  - name: nino
    rec:
      - { ip: 192.168.8.52, type: e, main: yes }
      - { ip: 192.168.8.62, type: w }

  - name: miku
    rec:
      - { ip: 192.168.8.53, type: e, main: yes }
      - { ip: 192.168.8.63, type: w }

  - name: yotsuba
    rec:
      - { ip: 192.168.8.54, type: e, main: yes }
      - { ip: 192.168.8.64, type: w }

  - name: itsuki
    rec:
      - { ip: 192.168.8.55, type: e, main: yes }
      - { ip: 192.168.8.65, type: w }

  - name: rikka
    rec:
      - { ip: 192.168.8.56, type: e, main: yes }
      - { ip: 192.168.8.66, type: w }

  - name: metroid
    rec:
      - { ip: 192.168.8.57, type: e, main: yes}
      - { ip: 192.168.8.67, type: w }

  - name: zelda
    rec:
      - { ip: 192.168.8.58, type: e, main: yes }
      - { ip: 192.168.8.68, type: w }

  - name: emily
    rec:
      - { ip: 192.168.8.69, type: w, main: yes }

  - name: yukinon
    rec:
      - { ip: 192.168.8.30, type: e }
      - { ip: 192.168.8.40, type: w, main: yes }

  - name: raphtalia
    rec:
      - { ip: 192.168.8.31, type: e }
      - { ip: 192.168.8.41, type: w, main: yes }
