###############################################################################
# Main options
###############################################################################
admins:
  - name: mak
    color: "01;33m"
    comment: "Mikhail Kucherenko"
    email: "makucherenko@list.ru"
    key: "https://github.com/snipghost.keys"
  - name: horifox
    color: "01;32m"
    comment: "Tagir Khanmurzin"
    email: "lhorifoxl@gmail.com"
    git_name: HoriFox
    key: "https://github.com/horifox.keys"
###############################################################################
# Path to SSD-disks for all disk-based services
data_path: "/mnt/data"
###############################################################################
# Network
default_gw: 192.168.8.1
subnet_mask: 24
secondary_dns: 8.8.8.8
#=====================================#
# External dashboards
public_vip_id:     1
public_vip_ip:     192.168.8.11
#=====================================#
# DNS & subservices
service_vip_id:    2
service_vip_ip:    192.168.8.12
#=====================================#
# Internal dashboards & SmartHome
private_vip_id:    3
private_vip_ip:    192.168.8.13
#=====================================#
# Monitoring services only
monitoring_vip_id: 4
monitoring_vip_ip: 192.168.8.14
#=====================================#
# Emulate public on dev-environment
dev_public_vip_id: 5
dev_public_vip_ip: 192.168.8.15
#=====================================#
# Machine learning services
research_vip_id:   6
research_vip_ip:   192.168.8.16
#=====================================#
#  Emulate private on dev-environment
dev_private_vip_id: 7
dev_private_vip_ip: 192.168.8.17
###############################################################################
# Chronyd options
ntpd_servers:
  - ntp1.mail.ru
  - ntp2.mail.ru
###############################################################################
# Logrotate
logrotate_default_period: weekly
logrotate_default_rotate: 4
###############################################################################
# Rsyslog
rsyslog_remote_logdir: /mnt/data/log
rsyslog_log_period:    daily
rsyslog_log_rotate:    7
rsyslog_log_size:      100M
rsyslog_send_facility:
  - auth
  - authpriv
  - local0
  - local7
rsyslog_send_severity:
  - '*'
rsyslog_server_udp: no
rsyslog_server_tcp: yes
rsyslog_remote_allowed:
  - 127.0.0.1
  - 192.168.8.0/24
###############################################################################
# Local DNS via dnsmasq
dnsmasq_records_file: /etc/cluster-hosts
dnsmasq_exporter_enabled: no
dnsmasq_logging: no
dnsmasq_iface: eth0:{{ service_vip_id }}
# DNS records in dns.yml
###############################################################################
# Prometheus
prometheus_data_retention: "60d"
prometheus_version: "2.23.0"
prometheus_jobs:
  - { name: node, port: 9100, group: all }
  - { name: haproxy, port: 9101, group: all }
  - { name: mysql, port: 9104, group: db_servers }
  - { name: nginx, port: 9113, group: web_servers }
  - { name: redis, port: 9121, group: redis_servers }
  - { name: memcached, port: 9150, group: memcached_servers }
  # - { name: dnsmasq, port: 9153, group: dns_servers }
  - { name: rpi, port: 9243, group: raspberry_pi }
###############################################################################
# Prometheus exporter's version
rpi_exporter_version: 0.6.0
node_exporter_version: 1.0.1
mysqld_exporter_version: 0.12.1
memcached_exporter_version: 0.8.0
haproxy_exporter_version: 0.12.0
redis_exporter_version: 1.17.1
nginx_exporter_scrape_uri: http://127.0.0.1/stub_status
###############################################################################
# Grafana
grafana_domain: grafana.assol.ml
###############################################################################
# Affect Nginx-ACL & iptables
external_blacklist:
  - 198.16.0.0/16       # Amsterdam Browsec VPN (test)
  - 220.145.227.70/32   # pmadmin|phpmyadmin
  - 185.142.236.43/32   # robots.txt|sitemap.xml
  - 46.101.146.208/32   # masscan
  - 139.59.226.79/32    # masscan
  - 209.97.134.32/32    # masscan
  - 35.195.161.121/32   # masscan
  - 208.91.111.234/32   # autoprpv
  - 173.242.104.172/32  # winnti-scanner-victims-will-be-notified
  - 60.60.141.209/32    # artemis.pokeradio.net
  - 209.141.60.60/32    # artemis.pokeradio.net
  - 52.42.79.222/32     # try wordpress/wp-login
  - 222.186.136.150/32  # unknown
  - 192.241.218.199/32  # try /owa/auth/logon.aspx
  - 138.68.249.116/32   # strange request
  - 139.162.145.250/32  # strange request
  - 192.241.228.12/32   # strange request
  - 193.118.53.210/32   # strange request
  - 201.245.168.163/32  # strange request
  - 39.96.137.146/32    # strange request
  - 39.96.139.120/32    # strange request
###############################################################################
