admins:
  - { name: mak, color: "01;33m", comment: "Mikhail Kucherenko", key: "https://github.com/snipghost.keys"}
  - { name: horifox, color: "01;32m", comment: "Tagir Khanmurzin", key: "https://github.com/horifox.keys"}

data_path: "/mnt/data"
prometheus_data_retention: "60d"
prometheus_version: "2.23.0"
prometheus_jobs:
  - { name: node, port: 9100, group: all }
  - { name: haproxy, port: 9101, group: all }
  - { name: mysql, port: 9104, group: db_servers }
  - { name: memcached, port: 9150, group: cache_servers }
  # - { name: dnsmasq, port: 9153, group: dns_servers }
  - { name: rpi, port: 9243, group: raspberry_pi }

rpi_exporter_version: 0.6.0
node_exporter_version: 1.0.1
mysqld_exporter_version: 0.12.1
memcached_exporter_version: 0.8.0
haproxy_exporter_version: 0.12.0

default_gw: 192.168.8.1
subnet_mask: 24
secondary_dns: 8.8.8.8

public_vip_id: 1
public_vip_ip: 192.168.8.11
public_vip_mask: "{{ subnet_mask }}"

service_vip_id: 2
service_vip_ip: 192.168.8.12
service_vip_mask: "{{ subnet_mask }}"

private_vip_id: 3
private_vip_ip: 192.168.8.13
private_vip_mask: "{{ subnet_mask }}"

dnsmasq_records_file: /etc/cluster-hosts
dnsmasq_exporter_enabled: no
dnsmasq_logging: no
dnsmasq_iface: eth0:{{ service_vip_id }}
dnsmasq_hosts:
  - { rec: [{ip: "{{service_vip_ip}}", type: vip}], name: service }
  - { rec: [{ip: "{{public_vip_ip}}", type: vip}], name: public }
  - { rec: [{ip: "{{private_vip_ip}}", type: vip}], name: private }
  - { rec: [{ip: 192.168.8.50, type: e, main: yes}, {ip: 192.168.8.60, type: w}], name: asuna }
  - { rec: [{ip: 192.168.8.51, type: e, main: yes}, {ip: 192.168.8.61, type: w}], name: ichika }
  - { rec: [{ip: 192.168.8.52, type: e, main: yes}, {ip: 192.168.8.62, type: w}], name: nino }
  - { rec: [{ip: 192.168.8.53, type: e, main: yes}, {ip: 192.168.8.63, type: w}], name: miku }
  - { rec: [{ip: 192.168.8.54, type: e, main: yes}, {ip: 192.168.8.64, type: w}], name: yotsuba }
  - { rec: [{ip: 192.168.8.55, type: e}, {ip: 192.168.8.65, type: w, main: yes}], name: itsuki }
  - { rec: [{ip: 192.168.8.56, type: e}, {ip: 192.168.8.66, type: w, main: yes}], name: rikka }
  - { rec: [{ip: 192.168.8.57, type: e}, {ip: 192.168.8.67, type: w, main: yes}], name: metroid }
  - { rec: [{ip: 192.168.8.30, type: e}, {ip: 192.168.8.40, type: w, main: yes}], name: yukinon }

mariadb_cluster_name: GaleraCluster
mariadb_bind_address: 0.0.0.0
mariadb_max_conn:     2048
mariadb_pool_size:    122M
mariadb_gcache_size:  200M
mariadb_gcache_page:  200M
mariadb_datadir:      /mnt/data/mysql
mariadb_socket:       /var/run/mysqld/mysqld.sock
mariadb_safe_hosts:
  - "localhost"
  - "127.0.0.1"
  - "192.168.8.5_" 

mariadb_proxy_port: 3307
mariadb_proxy_port_ro: 3308
mariadb_proxy_check_port: 9200
mariadb_l7_check: no

memcached_user:      memcached
memcached_port:      11211
memcached_max_conn:  1024
memcached_cachesize: 128

memcached_proxy_port: 11311

redis_bind_addr: 0.0.0.0
redis_bind_port: 6379
redis_db_count:  5

redis_proxy_port: 6380

haproxy_bind_ip: 0.0.0.0
haproxy_stat_uri: /haproxy_stats
haproxy_stat_host: 0.0.0.0
haproxy_stat_port: 9000
