groups:
  - name: special
    rules:
    
      - alert: RPiOverheat
        expr: rpi_cpu_temperature_celsius > 60
        for: 30s
        labels:
          severity: critical
          module: infra
        annotations:
          summary: "RPi CPU overheat detected (instance {{ $labels.instance }})"
          description: "{{ $labels.instance }} CPU temperature > 60 deg.C for 30s, VALUE = {{ $value }}."
      
      - alert: uWSGIAppNotRunning
        expr: node_systemd_unit_state{name=~"uwsgi-app@.+", state=~"inactive|deactivating|activating"} != 0
        for: 30s
        labels:
          severity: warning
          module: uwsgi
        annotations:
          summary: "{{ $labels.name }} uWSGI app not running (instance {{ $labels.instance }})"
          description: "Python uWSGI app {{ $labels.name }} on {{ $labels.instance }} state = {{ $labels.state }}, type = {{ $labels.type }}."

      - alert: RazumatorNotRunning
        expr: node_systemd_unit_state{name=~"razumator-.+", state=~"inactive|deactivating|activating"} != 0
        for: 30s
        labels:
          severity: warning
          module: razumator
        annotations:
          summary: "{{ $labels.name }} uWSGI app not running (instance {{ $labels.instance }})"
          description: "Python uWSGI app {{ $labels.name }} on {{ $labels.instance }} state = {{ $labels.state }}, type = {{ $labels.type }}."

      - alert: MysqlDown
        expr: mysql_up == 0
        for: 0m
        labels:
          severity: warning
          module: mysql
        annotations:
          summary: "MySQL down (instance {{ $labels.instance }})"
          description: "MySQL instance is down on {{ $labels.instance }}. VALUE = {{ $value }}."

      - alert: InsufficientCluster
        expr: (mysql_global_status_wsrep_cluster_status != 0) * (2 - mysql_global_status_wsrep_cluster_size > 0)
        for: 0m
        labels:
          severity: warning
          module: mysql
        annotations:
          summary: "MySQL insufficient cluster size (instance {{ $labels.instance }})"
          description: "Cluster size < 2 on {{ $labels.instance }} for active wsrep, VALUE = {{ $value }}."

      - alert: MarynoNetBalance
        expr: maryno_net_balance < (1.5 * maryno_net_plan_cost)
        for: 0m
        labels:
          severity: warning
          module: payment
        annotations:
          summary: "Low balance for internet provider (instance {{ $labels.instance }})"
          description: "Account balance < (1.5 * month_cost), balance = {{ $value }} rub."
      
      - alert: MarynoNetAccountLocked
        expr: maryno_net_is_blocked > 0
        for: 0m
        labels:
          severity: critical
          module: payment
        annotations:
          summary: "Maryno.net account locked (instance {{ $labels.instance }})"
          description: "Maryno.net account locked, maryno_net_is_blocked > 0, value = {{ $value }}."
        
      - alert: ConsulServiceIsDown
        expr: sum by (node, service_id)(consul_catalog_service_node_healthy{instance!="rikka:9107", instance!="itsuki:9107"} == 0)
        for: 1m
        labels:
          severity: critical
          module: consul
        annotations:
          summary: "Consul service check failed (service {{ $labels.service_id }})"
          description: "Health-check failed: consul_health_service_status > 0"
