---
- name: Add backup scripts
  template:
    src: "{{ item.tpl }}"
    dest: /etc/cron.{{ item.interval }}/{{ item.name | default(item.tpl) }}
    mode: 755
  notify: cron_restart
  with_items: "{{ backup_scripts | default([]) }}"

- name: Flush handlers
  meta: flush_handlers
