---
- name: restart nginx_exporter
  systemd:
    name: nginx_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: nginx_exporter_restarted
  when: not nginx_exporter_started.changed

- name: reload nginx_exporter
  systemd:
    name: nginx_exporter
    state: reloaded
  when: 
    - not nginx_exporter_started.changed
    - not (nginx_exporter_restarted.changed | default(false))
