---
- name: restart consul server
  systemd:
    name: consul
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: consul_restarted
  when: not consul_started.changed

- name: reload consul server
  systemd:
    name: consul
    state: reloaded
  when: 
    - not consul_started.changed
    - not (consul_restarted.changed | default(false))
