---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install packages
  package:
    name:
      - python
      - python-apt
      - git
      - vim
      - nano
      - tmux
      - dnsutils
      - tcpdump
      - net-tools
    state: present

- name: Create tmux-env
  copy:
    src: tmux-env.sh
    dest: /usr/local/bin/tmux-env
    mode: 0755
    owner: root
    group: root
