---
- name: Install MySQL client (for ansible tasks)
  package:
    name: mariadb-client
    state: present

- name: Clone repo
  git:
    repo: "{{ krionard_git }}"
    dest: "{{ krionard_bindir }}"
    clone: yes
    update: yes
  notify:
    - app_restart

- name: Reset permissions
  file:
    path: "{{ krionard_bindir }}"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: u=rwX,g=rwX,o=rX
    recurse: yes

- name: Creating app user group
  group: name="{{groupId}}"

- name: Creating app user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Add admin users to app group
  user:
    name: "{{ item.name }}"
    groups: "{{ groupId }}"
    append: yes
  with_items: "{{ admins }}"

- name: Create uwsgi-app-config
  template:
    src: uwsgi-app.ini.j2
    dest: /etc/uwsgi/apps-available/{{ app_name }}.ini
    mode: 0644
    owner: root
    group: root
  notify:
    - app_restart

- name: Create a symbolic link in apps-enabled
  file:
    src: /etc/uwsgi/apps-available/{{ app_name }}.ini
    dest: /etc/uwsgi/apps-enabled/{{ app_name }}.ini
    owner: root
    group: root
    mode: 0644
    state: link
  notify:
    - app_restart

- name: Create path for working directory
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - path: "{{ krionard_logdir }}"
      owner: "{{ userId }}"
      group: "{{ groupId }}"
    - path: "{{ krionard_confdir }}"
      owner: "{{ userId }}"
      group: "{{ groupId }}"

- name: Copy logrotate config file
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/{{ app_name }}
  notify: logrotate_restart

- name: Delete invalid rsyslog config
  file:
    path: /etc/rsyslog.d/{{ app_name }}
    state: absent
  notify: rsyslog_restart

- name: Copy rsyslog config file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/98-{{ app_name }}.conf
  notify: rsyslog_restart

- name: Create app config
  template:
    src: "{{ item.src }}"
    dest: "{{ krionard_confdir }}/{{ item.dest }}"
    mode: 0660
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    backup: yes
  with_items:
    - { src: app.config.json.j2, dest: skill.config.json }
  notify:
    - app_restart

- name: Copy vocabulary
  ansible.builtin.copy:
    src: "{{ krionard_bindir }}/config_copy/skill.vocabulary.json"
    dest: "{{ krionard_confdir }}/skill.vocabulary.json"
    mode: 0660
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    remote_src: yes
    backup: yes
  notify:
    - app_restart

- name: Create venv and install requirements
  pip: 
    requirements: "{{ krionard_bindir }}/dependencies/requirements.txt"
    virtualenv: "{{ krionard_bindir }}/env"
    virtualenv_python: python3.7
  notify:
    - app_restart

- name: Retrieve db user grants from mysql
  shell: /usr/bin/mysql -u sst_user -p'{{ mariadb_sst_pass }}' --host {{ mariadb_proxy_host }} -P {{ mariadb_proxy_port }} -e "select Host, User from mysql.user where User = '{{ krionard_db_user }}';" --batch --skip-column-names
  register: stuff
  check_mode: no
  changed_when: False
  when: (inventory_hostname == groups[krionard_group][0])

- name: Revoke all grant for db user
  vars:
    userhost: "'{{ item.split('\t')[1] }}'@'{{ item.split('\t')[0] }}'"
  shell: /usr/bin/mysql -u sst_user -p'{{ mariadb_sst_pass }}' --host {{ mariadb_proxy_host }} -P {{ mariadb_proxy_port }} -ne "DROP USER {{ userhost }};"
  with_items: "{{ stuff.stdout_lines }}"
  when: (inventory_hostname == groups[krionard_group][0]) and (item.split('\t')[0] not in mariadb_safe_hosts)

- name: Add db user to mysql
  shell: /usr/bin/mysql -u sst_user -p'{{ mariadb_sst_pass }}' --host {{ mariadb_proxy_host }} -P {{ mariadb_proxy_port }} -ne "GRANT SELECT, INSERT, DELETE, UPDATE ON {{ krionard_db_name }}.* TO '{{ krionard_db_user }}'@'{{ item }}' IDENTIFIED BY '{{ krionard_db_pass }}';"
  with_items: "{{ mariadb_safe_hosts }}"
  changed_when: False
  when: (inventory_hostname == groups[krionard_group][0])

- name: Re-create db
  shell: /usr/bin/mysql -u sst_user -p'{{ mariadb_sst_pass }}' --host {{ mariadb_proxy_host }} -P {{ mariadb_proxy_port }} < {{ krionard_bindir }}/sql_setup/marusyatech.sql 
  when: (inventory_hostname == groups[krionard_group][0]) and (krionard_setup | default(false) | bool)

- meta: flush_handlers

- name: Start and enable uwsgi-app
  systemd:
    name: "uwsgi-app@{{ app_name }}"
    state: started
    enabled: yes
