---
- name: nginx_reload
  systemd:
    name: nginx
    state: reloaded

- name: nginx_restart
  systemd:
    name: nginx
    state: restarted

- name: restart certbot
  systemd:
    name: certbot
    state: restarted
    daemon_reload: yes
