---
- name: Create repo file
  template:
    src: pdns.list.j2
    dest: /etc/apt/sources.list.d/pdns.list
    owner: root
    group: root
    mode: 0644

# View manual at: https://repo.powerdns.com/
- name: Add an PowerDNS repo key
  apt_key:
    url: https://repo.powerdns.com/FD380FBB-pub.asc
    state: present

- name: Install PowerDNS packages
  package:
    name:
      - pdns-server
      - pdns-tools
      - pdns-backend-mysql
    state: latest

- name: Create system group
  group:
    name: "{{ groupId }}"
    system: yes
    state: present
  when: groupId != 'root'

- name: Create system user
  user:
    name: "{{ userId }}"
    system: yes
    shell: "/usr/sbin/nologin"
    group: "{{ groupId }}"
    createhome: no
    home: /var/lib/{{ serviceName }}
  when: groupId != 'root'
