---
- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

- name: Restart rpi_exporter service
  service:
    name: rpi_exporter
    state: restarted
  listen: rpi_exporter_restart
