---
- name: Install packages
  package:
    name:
      - keepalived
    state: present
  when: keepalived_vips is defined

- name: Create config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: keepalived_restart
  when: keepalived_vips is defined

- name: Check that config file exists
  stat:
    path: /etc/keepalived/keepalived.conf
  register: stat_result
  when: keepalived_vips is not defined

- name: Stop keepalived service
  service:
    name: keepalived
    state: stopped
    enabled: no
  when: keepalived_vips is not defined and stat_result.stat.exists

- meta: flush_handlers

- name: Start keepalived service
  service:
    name: keepalived
    state: started
    enabled: yes
  when: keepalived_vips is defined
