---
- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

- name: Restart the Alertmanager service
  service:
    name: alertmanager
    state: restarted
  listen: alertmanager_restart
