---
- name: restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: alertmanager_restarted
  when: not alertmanager_started.changed

- name: reload alertmanager
  systemd:
    name: alertmanager
    state: reloaded
  when: 
    - not alertmanager_started.changed
    - not (alertmanager_restarted.changed | default(false))
