# Main options for dev-all only

# MariaDB/MySQL/Galera options
mariadb_cluster_name: GaleraClusterDev
mariadb_bind_address: 0.0.0.0
mariadb_max_conn: 512
mariadb_pool_size: 60M
mariadb_gcache_size: 100M
mariadb_gcache_page: 100M
mariadb_data_dir: "{{data_path}}/mysql"
mariadb_socket: /var/run/mysqld/mysqld.sock
mariadb_safe_hosts:
  - "localhost"
  - "127.0.0.1"
  - "192.168.8.5_"
  - "192.168.8.6_"
# MariaDB proxy options
mariadb_proxy_host: 127.0.0.1
mariadb_proxy_port: 3307
mariadb_proxy_port_ro: 3308
mariadb_proxy_check_port: 9200
mariadb_l7_check: no

# PostgreSQL
postgresql_host: 0.0.0.0
postgresql_port: 5432
postgresql_max_conn: 256
postgresql_main_dir: /mnt/data/postgresql
postgresql_data_dir: /mnt/data/postgresql/main
postgresql_shared_buffer: "32MB"
postgresql_max_wal_size: "500MB"
postgresql_min_wal_size: "80MB"
postgresql_cluster_name: "11/main/dev"
postgresql_safe_hosts:
  - "127.0.0.1/32"
  - "192.168.8.0/24"
postgresql_replication: no
postgresql_max_wal_senders: "{{ (groups[db_group] | length) * 2 }}"
postgresql_max_replication_slots: "{{ postgresql_max_wal_senders }}"
# PostgreSQL proxy options
postgresql_proxy_host: 127.0.0.1
postgresql_proxy_port: 5433
postgresql_proxy_port_ro: 5434

# Memcached
memcached_user: memcached
memcached_host: "{{ lookup('dig', inventory_hostname + '.i') }}"
memcached_port: 11211
memcached_max_conn: 512
memcached_cachesize: 64
# Memcached proxy options
memcached_proxy_host: 127.0.0.1
memcached_proxy_port: 11311

# Redis
redis_bind_addr: "{{ lookup('dig', inventory_hostname + '.i') }}"
redis_bind_port: 6379
redis_db_count: 5
redis_data_path: "{{ data_path }}/redis/"
# Redis proxy options
redis_proxy_host: 127.0.0.1
redis_proxy_port: 6380

# HAProxy
haproxy_bind_ip: 127.0.0.1
haproxy_stat_uri: /haproxy_stats
haproxy_stat_host: 127.0.0.1
haproxy_stat_port: 9000
