---
- name: Creates data directory
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0755
  with_items:
    - "{{ victoria_metrics_data_path }}"
    - "{{ vmagent_data_path }}"

- name: Creates config directory
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copy limits conf file
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.d/victoria-metrics.conf
  notify: victoria-metrics restart

- name: Copy victoria-metrics systemd init file
  vars:
    item: victoria-metrics
  template:
    src: init.service.j2
    dest: /etc/systemd/system/{{ item }}.service
  notify: "{{ item }} restart"

- name: Copy vmagent systemd init file
  vars:
    item: vmagent
  template:
    src: init.service.j2
    dest: /etc/systemd/system/{{ item }}.service
  notify: "{{ item }} restart"
  when: victoria_metrics_vmagent_enabled | default(false) | bool

- name: Copy vmalert systemd init file
  vars:
    item: vmalert
  template:
    src: init.service.j2
    dest: /etc/systemd/system/{{ item }}.service
  notify: "{{ item }} restart"

- name: Copy config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/victoria-metrics.conf
  notify:
    - victoria-metrics restart
    - vmagent restart

- name: Copy rule files
  copy:
    src: "files/{{ item }}"
    dest: /etc/prometheus/
  with_items: "{{ victoria_metrics_rule_files }}"
  notify: vmalert restart

- name: Start Victoria Metrics service
  service:
    name: victoria-metrics
    state: started
    daemon_reload: yes
    enabled: yes
  register: victoria_metrics_started

- name: Start vmagent service
  service:
    name: vmagent
    state: started
    daemon_reload: yes
    enabled: yes
  register: vmagent_started
  when: victoria_metrics_vmagent_enabled | default(false) | bool

- name: Start vmalert service
  service:
    name: vmalert
    state: started
    daemon_reload: yes
    enabled: yes
  register: vmalert_started
