---
- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

- name: Restart logrotate service
  service:
    name: logrotate
    state: restarted
  listen: logrotate_restart

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  listen: rsyslog_restart

- name: Restart uwsg-app service
  service:
    name: "uwsgi-app@{{ app_name }}"
    state: restarted
  listen: app_restart
