#!/bin/sh
BACKUP_SRC={{ item.backup_src }}
BACKUP_DIR={{ item.backup_dir }}
BACKUP_EXT={{ item.backup_ext | default('tar.bz2') }}
BACKUP_OPTS={{ item.opts | default('cfj') }}

mkdir -p $BACKUP_DIR
tar $BACKUP_OPTS ${BACKUP_DIR}/$(date '+%d.%m.%Y-%H:%M:%S').${BACKUP_EXT} ${BACKUP_SRC}/
find ${BACKUP_DIR}/ -mtime +{{ item.retention }} -type f -iname "*.${BACKUP_EXT}" -delete

# To restore archive.tar.bz2 to real path run:
# tar xfvj archive.tar.bz2 -C /
