---
- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/haproxy_exporter.service
  notify: restart haproxy_exporter

- name: Start haproxy_exporter service
  systemd:
    name: haproxy_exporter
    state: started
    daemon_reload: yes
    enabled: yes
  register: haproxy_exporter_started
