groups:
  - name: special
    rules:
    
      - alert: RPiOverheat
        expr: rpi_cpu_temperature_celsius > 60
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "RPi CPU overheat detected (instance {{ $labels.instance }})"
          description: "{{ $labels.instance }} CPU temperature > 60 deg.C for 30s, VALUE = {{ $value }}."
      
      - alert: uWSGIAppNotRunning
        expr: node_systemd_unit_state{name=~"uwsgi-app@.+", state="active"} != 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.name }} uWSGI app not running (instance {{ $labels.instance }})"
          description: "Python uWSGI app {{ $labels.name }} on {{ $labels.instance }} state = {{ $labels.state }}, type = {{ $labels.type }}."

      - alert: RazumatorNotRunning
        expr: node_systemd_unit_state{name=~"razumator-.+", state="active"} != 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.name }} uWSGI app not running (instance {{ $labels.instance }})"
          description: "Python uWSGI app {{ $labels.name }} on {{ $labels.instance }} state = {{ $labels.state }}, type = {{ $labels.type }}."

      - alert: MysqlDown
        expr: mysql_up == 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "MySQL down (instance {{ $labels.instance }})"
          description: "MySQL instance is down on {{ $labels.instance }}. VALUE = {{ $value }}."

      - alert: InsufficientCluster
        expr: (mysql_global_status_wsrep_cluster_status != 0) * (2 - mysql_global_status_wsrep_cluster_size > 0)
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "MySQL insufficient cluster size (instance {{ $labels.instance }})"
          description: "Cluster size < 2 on {{ $labels.instance }} for active wsrep, VALUE = {{ $value }}."

      # - alert: NginxHighHttp5xxErrorRate
      #   expr: sum(rate(nginx_http_requests_total{status=~"^5.."}[1m])) / sum(rate(nginx_http_requests_total[1m])) * 100 > 5
      #   for: 1m
      #   labels:
      #     severity: warning
      #   annotations:
      #     summary: "Nginx high HTTP 5xx error rate (instance {{ $labels.instance }})"
      #     description: "Too many HTTP requests with status 5xx (> 5%). VALUE = {{ $value }}. LABELS: {{ $labels }}."

      # - alert: NginxHighHttp4xxErrorRate
      #   expr: sum(rate(nginx_http_requests_total{status=~"^4.."}[1m])) / sum(rate(nginx_http_requests_total[1m])) * 100 > 5
      #   for: 1m
      #   labels:
      #     severity: critical
      #   annotations:
      #     summary: "Nginx high HTTP 4xx error rate (instance {{ $labels.instance }})"
      #     description: "Too many HTTP requests with status 4xx (> 5%). VALUE = {{ $value }}. LABELS: {{ $labels }}."
