---
- name: Creating prometheus user group
  group: name="{{groupId}}"

- name: Creating prometheus user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin user"
    createhome: "no"
    state: present

- name: Install prometheus
  unarchive:
    src: 'https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ proc_version }}.tar.gz'
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus file to bin
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ proc_version }}/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    remote_src: yes
    mode: 0755

- name: Delete prometheus tmp folder
  file:
    path: '/tmp/prometheus-{{ prometheus_version }}.linux-{{ proc_version }}'
    state: absent

- name: Creates data directory
  file: 
    path: "{{ data_path }}/prometheus/"
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0755

- name: Creates config directory
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Copy config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf
  notify: prometheus_restart

- meta: flush_handlers

- name: Start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Check if prometheus is accessible
  uri:
    url: http://127.0.0.1:9090/
    method: GET
    status_code: 200
