---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install packages
  package:
    name:
      - python-apt
      - python3-pip
      - git
      - vim
      - nano
      - tmux
      - dnsutils
      - tcpdump
    state: present

- name: Write dhcpcd config for static IP
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    backup: yes
    mode: 0664
    owner: root
    group: netdev
  when: "inventory_hostname in groups['raspberry_pi']"

- name: Configurate WiFi
  shell: "raspi-config nonint do_wifi_ssid_passphrase {{ ap_ssid }} {{ ap_pass }} && raspi-config nonint do_wifi_country {{ ap_code }}"
  when: "inventory_hostname in groups['raspberry_pi']"

- name: Install Golang
  unarchive:
    src: "https://golang.org/dl/go1.15.6.linux-armv6l.tar.gz"
    dest: /usr/local/
    remote_src: yes
  when: "inventory_hostname in groups['raspberry_pi']"
