---
- name: Create hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install packages
  package:
    name:
      - python
      - python3
      - python-apt
      - python-pip
      - python3-pip
      - git
      - vim
      - nano
      - tmux
      - dnsutils
      - tcpdump
      - lvm2
      - python-pymysql
    state: present

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: Install Golang
  unarchive:
    src: "https://golang.org/dl/go1.15.6.linux-armv6l.tar.gz"
    dest: /usr/local/
    remote_src: yes
  when: "inventory_hostname in groups['raspberry_pi']"

- name: Manage sysctl
  include_tasks: sysctl.yml
