---
- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

- name: Restart redis_exporter service
  service:
    name: redis_exporter
    state: restarted
  listen: redis_exporter_restart
