---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: Create docker-daemon config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  notify:
    - docker_restart

- meta: flush_handlers

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes