###############################################################################
# Main options for dev-all only
###############################################################################
mariadb_cluster_name: GaleraClusterDev
mariadb_bind_address: 0.0.0.0
mariadb_max_conn:     512
mariadb_pool_size:    60M
mariadb_gcache_size:  100M
mariadb_gcache_page:  100M
mariadb_datadir:      /mnt/data/mysql
mariadb_socket:       /var/run/mysqld/mysqld.sock
mariadb_safe_hosts:
  - "localhost"
  - "127.0.0.1"
  - "192.168.8.5_" 
# MariaDB proxy options
mariadb_proxy_port:       3307
mariadb_proxy_port_ro:    3308
mariadb_proxy_check_port: 9200
mariadb_l7_check:         no
###############################################################################
# Memcached
memcached_user:      memcached
memcached_port:      11211
memcached_max_conn:  512
memcached_cachesize: 64
# Memcached proxy options
memcached_proxy_port: 11311
###############################################################################
# Redis
redis_bind_addr: 0.0.0.0
redis_bind_port: 6379
redis_db_count:  5
# Redis proxy options
redis_proxy_port: 6380
###############################################################################
# HAProxy
haproxy_bind_ip:   0.0.0.0
haproxy_stat_uri:  /haproxy_stats
haproxy_stat_host: 0.0.0.0
haproxy_stat_port: 9000
###############################################################################
# NGINX options
default_cert:         /etc/nginx/certs/dev-assol.ml.fullchain.pem
default_cert_key:     /etc/nginx/certs/dev-assol.ml.privkey.pem
nginx_enable_default: yes
# Get only names: nginx_sites | map(attribute='name') | flatten
nginx_sites:
  - name: smarthome
    server_name: smarthome.dev-assol.ml
    addr: "{{ dev_private_vip_ip }}"
    group: "{{ smarthome_group }}"
    static_root: /usr/local/bin/smarthome/static
    static_path: /static
    # local: yes # No load balancing, only failover
    port: "{{ smarthome_port }}"
    hosts: dev_private_hosts
    whitelist:
      - vpn
    display:
      name: SmartHome
      icon: smarthome.svg
  - name: marusya_skill
    server_name: marusya.dev-assol.ml
    addr: "{{ dev_public_vip_ip }}"
    group: "{{ marusya_skill_group }}"
    # local: yes # No load balancing, only failover
    port: "{{ marusya_skill_port }}"
    hosts: dev_public_hosts
    whitelist:
      - vpn
    display:
      name: Маруся
      icon: marusya.png
  - name: haproxy
    server_name: haproxy_{{ inventory_hostname }}.assol.ml
    addr: "{{ lookup('dig', inventory_hostname + '.local') }}"
    add_path: /haproxy_stats
    local: yes
    port: "{{ haproxy_stat_port }}"
    ssl_certificate: /etc/nginx/certs/assol.ml.fullchain.pem
    ssl_certificate_key: /etc/nginx/certs/assol.ml.privkey.pem
    whitelist:
      - vpn
    display:
      name: HAProxy
      icon: haproxy.png
  - name: external-dashboard
    server_name: dev-assol.ml
    addr: "{{ dev_public_vip_ip }}"
    static_root: "{{ dashboard_path }}external/"
    static_path: /
    static_hard: yes
    ignore_not_found: yes
    whitelist:
      - vpn
    display:
      name: External
      icon: external.png
  - name: internal-dashboard
    server_name: internal.dev-assol.ml
    addr: "{{ dev_private_vip_ip }}"
    static_root: "{{ dashboard_path }}internal/"
    static_path: /
    static_hard: yes
    hosts: dev_private_hosts
    whitelist:
      - vpn
  - name: swagger
    server_name: swagger.dev-assol.ml
    addr: "{{ dev_private_vip_ip }}"
    static_root: "{{ swagger_path }}"
    static_path: /
    static_hard: yes
    hosts: dev_private_hosts
    whitelist:
      - vpn
    display:
      name: Swagger
      icon: swagger.svg
  - name: mdwiki
    server_name: wiki.dev-assol.ml
    addr: "{{ dev_private_vip_ip }}"
    static_root: "{{ mdwiki_path }}"
    static_path: /
    static_hard: yes
    hosts: dev_private_hosts
    whitelist:
      - vpn
    display:
      name: Wiki
      icon: wiki.png
###############################################################################
# Dashboards only
dashboard_path:       /var/www/html/
dashboard_git:        git@github.com:SnipGhost/cluster-page.git
dashboard_max_width:  90vw
dashboard_top_margin: 20vh
swagger_path:         /var/www/html/swagger
swagger_git:          git@github.com:SnipGhost/custom-swagger.git
mdwiki_path:          /var/www/html/mdwiki/
display_only_sites:
  - name: Кластер
    addr: https://internal.dev-assol.ml/cluster/
    icon: cluster.svg
###############################################################################
