rsyslog_remote_log_dir: /mnt/data/log
rsyslog_log_period:    daily
rsyslog_log_rotate:    7
rsyslog_log_size:      100M

rsyslog_send_facility:
  - auth
  - authpriv
  - local0
  - local7

rsyslog_send_severity:
  - '*'

rsyslog_server: no
rsyslog_server_udp: no
rsyslog_server_tcp: yes
rsyslog_remote_allowed:
  - 127.0.0.1
