---
- hosts: all
  roles:
    - name: common
      tags: common
    - name: users
      tags: users
    - name: sshd
      tags: sshd
    - name: iptables
      tags:
        - iptables
        - acl
    - name: smartmon
      tags: smartmon
    - name: logrotate
      tags: logrotate
    - name: rsyslog
      tags: rsyslog
    - name: atop
      tags: atop
    - name: ntpd
      tags: ntpd
    - name: keepalived
      tags: keepalived
    - name: haproxy
      tags: haproxy
    - name: haproxy_exporter
      tags: haproxy_exporter
    - name: node_exporter
      tags: node_exporter
