---
- hosts: dns_servers
  roles:
    # Deprecated!
    # - name: dnsmasq
    #   tags:
    #     - dnsmasq
    #     - dns
    # - name: dnsmasq_exporter
    #   tags: dnsmasq_exporter
    - name: pdns_server
      tags:
        - pdns
        - pdns_server
        - dns
    - name: pdns_recursor
      tags:
        - pdns
        - pdns_recursor
        - dns
    - name: docker
      tags:
        - pdns
        - pdns_admin
        - dns
    - name: pdns_admin
      tags:
        - pdns
        - pdns_admin
        - dns

- hosts: rsyncd_servers
  pre_tasks:
    - name: Gather facts from all hosts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
      tags:
        - rsyncd
        - certs
  roles:
    - name: rsyncd
      tags:
        - rsyncd
        - certs
