---
- hosts: db_servers
  roles:
    # Unsafe: -e mariadb_rejoin=yes
    - name: mariadb
      tags: mariadb
    - name: mysqld_exporter
      tags: mysqld_exporter
    # Unsafe: -e pg_setup=yes
    - name: postgresql
      tags: postgresql
    - name: postgres_exporter
      tags: postgres_exporter

- hosts: memcached_servers
  roles:
    - name: memcached
      tags: memcached
    - name: memcached_exporter
      tags: memcached_exporter

- hosts: redis_servers
  roles:
    - name: redis
      tags: redis
    - name: redis_exporter
      tags: redis_exporter
