---
- name: Create config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: sshd_reload

- meta: flush_handlers

- name: Start sshd service
  service:
    name: sshd
    state: started
    enabled: yes